site_name: WebSphere Hybrid Edition - Application Modernization PoT
nav:
  - Home: index.md
  - Workshop Labs: day1.md
  - Accessing lab environments: lab-env.md
theme: readthedocs 
extra_css: ["extra.css"]
